python train/distill_nsa.py \
    --model /root/autodl-tmp/models/Llama-3.1-8B-Instruct \
    --real-fsa \
    --seqlen 512 \
    --batch 2 \
    --grad-accum 4 \
    --lr 4.114514e-4 \
    --warmup-steps 4 \
    --min-lr-ratio 0.01 \
    --logit-kl-weight 1.5 \
    --logit-kl-last-k 128 \
    --logit-temperature 2.0 \
    --max-tokens 191981 \
    --save-steps 320 \
    --save-dir /root/autodl-tmp/nsa_ckpt_tinystories_phase2 \
    --init-ckpt /root/autodl-tmp/nsa_ckpt_tinystories/step_001024 \
    --layers all \
    --topk 16 \
    --local-data /root/autodl-tmp/tinystories_128M.pt
