python train/distill_nsa.py   \
    --model /root/autodl-tmp/models/Llama-3.1-8B-Instruct \
    --real-fsa   \
    --seqlen 1024   \
    --batch 1   \
    --grad-accum 2   \
    --lr 2.0919810114514e-5    \
    --logit-kl-weight 0.5   \
    --logit-kl-last-k 8   \
    --logit-temperature 2.0   \
    --max-tokens 5114514   \
    --save-steps 1024   \
    --save-dir /root/autodl-tmp/nsa_ckpt  \
    --layers all   \
    --topk 16  \
    --local-data /root/autodl-tmp/c4_200M.pt
