python train/distill_nsa_v2.py \
    --model /root/autodl-tmp/models/Llama-3.1-8B-Instruct \
    --seqlen 1024 \
    --batch 1 \
    --grad-accum 1 \
    --lr 1.001451419e-5 \
    --warmup-steps 4 \
    --min-lr-ratio 0.08114514 \
    --logit-kl-weight 3.0 \
    --logit-kl-last-k 512 \
    --logit-temperature 1.6 \
    --max-tokens 2114514 \
    --save-steps 114514 \
    --save-dir /root/autodl-tmp/nsa_ckpt_simplebooks \
    --init-ckpt /root/autodl-tmp/nsa_ckpt_simplebooks/final \
    --layers all \
    --topk 16 \
    --local-data /root/autodl-tmp/simplebooks_94M.pt
